name: Gradle Test
# From github/docs, commit a926da8 building-and-testing-java-with-gradle.md

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Gradle
        run: ./gradlew test
