name: Gradle Build & Test
# From github/docs, commit a926da8 building-and-testing-java-with-gradle.md

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew build
      - run: ./gradlew test
